# Generated by Django 6.0 on 2025-12-15 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Time when the anomaly was detected.')),
                ('anomaly_type', models.CharField(choices=[('irrigation_issue', 'Irrigation issue'), ('heat_stress', 'Heat stress'), ('cold_stress', 'Cold stress'), ('sensor_malfunction', 'Sensor malfunction'), ('general_anomaly', 'General anomaly')], default='general_anomaly', max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('model_confidence', models.FloatField(help_text='Confidence score from the ML model (0.0–1.0).')),
                ('details', models.JSONField(blank=True, help_text='Optional JSON field for extra model details/context.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='farms.fieldplot')),
                ('sensor_reading', models.ForeignKey(blank=True, help_text='Reading that triggered this anomaly (if applicable).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='sensors.sensorreading')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
