from django.db import models

from ml_module.models import AnomalyEvent


class AgentRecommendation(models.Model):
    """
    Recommendation generated by the rule-based AI agent for a given anomaly.

    Explanations are deterministic and template-based, as required by the subject.
    """

    CONFIDENCE_LOW = "low"
    CONFIDENCE_MEDIUM = "medium"
    CONFIDENCE_HIGH = "high"

    CONFIDENCE_CHOICES = [
        (CONFIDENCE_LOW, "Low"),
        (CONFIDENCE_MEDIUM, "Medium"),
        (CONFIDENCE_HIGH, "High"),
    ]

    anomaly_event = models.ForeignKey(
        AnomalyEvent,
        on_delete=models.CASCADE,
        related_name="recommendations",
    )
    timestamp = models.DateTimeField(auto_now_add=True)
    recommended_action = models.CharField(max_length=255)
    explanation_text = models.TextField()
    confidence = models.CharField(
        max_length=10,
        choices=CONFIDENCE_CHOICES,
        default=CONFIDENCE_MEDIUM,
        help_text="Qualitative confidence level for this recommendation.",
    )

    class Meta:
        ordering = ["-timestamp"]

    def __str__(self) -> str:
        return f"Recommendation for {self.anomaly_event} ({self.confidence})"
