# Generated by Django 6.0 on 2025-12-15 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('sensor_type', models.CharField(choices=[('moisture', 'Soil moisture'), ('temperature', 'Air temperature'), ('humidity', 'Air humidity')], max_length=20)),
                ('value', models.DecimalField(decimal_places=3, help_text='Raw sensor value (units depend on sensor type).', max_digits=7)),
                ('source', models.CharField(choices=[('simulator', 'Simulator'), ('real_sensor', 'Real sensor')], default='simulator', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to='farms.fieldplot')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['plot', 'timestamp'], name='sensors_sen_plot_id_70314a_idx'), models.Index(fields=['sensor_type', 'timestamp'], name='sensors_sen_sensor__f7753b_idx')],
            },
        ),
    ]
