# Generated by Django 6.0 on 2025-12-15 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('size_hectares', models.DecimalField(blank=True, decimal_places=2, help_text='Approximate farm size in hectares.', max_digits=7, null=True)),
                ('crop_type', models.CharField(blank=True, help_text='Main crop type grown on this farm (e.g. Wheat, Corn).', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_variety', models.CharField(blank=True, help_text='Specific crop variety planted in this plot.', max_length=100)),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, help_text='Plot size in hectares.', max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='farms.farmprofile')),
            ],
            options={
                'ordering': ['farm', 'name'],
                'unique_together': {('farm', 'name')},
            },
        ),
    ]
