# Generated by Django 6.0 on 2025-12-15 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ml_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recommended_action', models.CharField(max_length=255)),
                ('explanation_text', models.TextField()),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Qualitative confidence level for this recommendation.', max_length=10)),
                ('anomaly_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='ml_module.anomalyevent')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
